language: python
python: 3.6
script: python setup.py test
deploy:
  provider: pypi
  user: __token__
  password:
    secure: KFn72EciXGo7gWpAOpQm+I5KC3Rrty7uupczbyiq2mAW/HREgFzCJ5YyrNth/DLQ3QfFaWi/RB9oQa4JkBhN2qWp/+dNpdW14/OKXztyUbFcDq4gAcAdEFUSK9+RAX1gnbI3IJe38sKwjqEqvFGUC1imklgLJ6owl7drUX1J+2u6zPzJPkrJlC2F5nY6t0204aUZo2p7NrDUWvtn9bMyOLw/8otUTNWYLvsiap8n+Yar7dsxRfaivaOoTXQ1VRIv4vmsEbQeSHGLVznlhBVubyVhZjp2PwlGjb2nyeDKF+Bjex9W+qj1L5IH15p8+TyqMNEPQhA8EE14i/R15DOznR7bozlaaBrSOyjXElQ26p5lViEBLlvhGoExQ2DZp+k9rC3kGoHZ7cG2F3ez0mSE4shVxnna/AkS94F5Gh0tp9WdSDMvNNa0IdKU+sJ3OMDCzuJHWtEghOBGUQFXNP6dR2JeUTrEXckvcHi1+g7WYNLUw2WsEdI4/IBTWAdztNgZ7Dnyg6a0jDnNqJOhrJGKMoca1TLDxyu8ENq52d/Yr+TBhUm8eoN9HV0+VUasDF73LEAdCP8eSZri/451b8xxwXedF7Xx5jDh7N95db5yqcexWbBpLfnX6273U9eNtgZRVtJc4e4pOTbNjZn5v41idVwzd0LCosRJoxIgpGSitP4=
  on:
    tags: true
    python: 3.6
  distributions: sdist bdist_wheel
